CREATE DATABASE lmdb
GO

CREATE LOGIN lm WITH PASSWORD = 'lm', DEFAULT_DATABASE=[lmdb], CHECK_EXPIRATION=OFF, CHECK_POLICY=OFF
GO

USE lmdb
CREATE USER lm FOR LOGIN lm
GO

GRANT ALTER, REFERENCES, INSERT, SELECT, UPDATE, DELETE ON DATABASE :: lmdb TO lm